[package]
name = "canary-core"
description = "Canary core engine — pass scheduler, incremental analysis database, commit/validate"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
canary-ir = { path = "../canary-ir" }
canary-analysis = { path = "../canary-analysis" }
canary-arch = { path = "../canary-arch" }
canary-emit = { path = "../canary-emit" }
canary-sdb = { path = "../canary-sdb" }
canary-constraints = { path = "../canary-constraints" }
canary-loader = { path = "../canary-loader" }
canary-plugin-api = { path = "../canary-plugin-api" }
canary-typerecov = { path = "../canary-typerecov" }
canary-cpprecov = { path = "../canary-cpprecov" }
indexmap.workspace = true
rustc-hash.workspace = true
thiserror.workspace = true
tracing.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
cpp_demangle = "0.5.1"
msvc-demangler = "0.11.0"
dashmap = "6.2.1"
crossbeam-queue = "0.3.12"
rayon = "1.12.0"
parking_lot = "0.12.5"

[dev-dependencies]
canary-arch-x86 = { path = "../canary-arch-x86" }
